### ISSUE TITLE
不支持 Windows

### ISSUE THREAD

**Issue by cupools** [cupools/emilia#1]
1. Windows 下路径中的反斜杠没有正确处理
2. `child_process.execFileSync` 抛出异常

**Comment by grantCHG** [comment]
什么时候会修好

**Comment by cupools** [comment]
这周末如果不需要加班就把这个干掉😢

**Comment by cupools** [comment]
@a521000362 问题已经修复啦，是由于 `child_process.execFileSync` 的不恰当使用造成的，具体原因见 [sprite.js](https://github.com/cupools/emilia/commit/09722ce6a3edddb5c6e236ff73bfe7817223f58d#diff-c277c642261076e468abf81151973d49R48)，很抱歉之前没在 Windows 验证过造成这个大坑😢

然后 `fis3-spriter-emilia` 我再更新下

**Comment by cupools** [comment]
Fixed in `v0.1.0`
